/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.aylex.dit

import org.aylex.dit.dsl.*

class TaxCalculator() {
    private var taxBrackets = listOf<TaxBracket>();

    constructor(taxBrackets: List<TaxBracket>) : this() {
        this.taxBrackets = taxBrackets
    }

    fun calculateTax(income: Income): Euro {
        var tax: Euro = Euro.of(0)
        for (taxBracket: TaxBracket in taxBrackets) {
            tax = tax.add(taxBracket.calculateTax(income))
        }
        return tax;
    }
}

fun main(args: Array<String>) {
    val income = box1Income{ amount = "€ 10" }
    val taxCalculator = taxCalculator {
        taxBrackets {
            taxBracket {
                min = "EUR 0"
                minIncome {
                    amount = "EUR 0"
                }
                max = "EUR 5"
                maxIncome {
                    amount = "EUR 5"
                }
                tax = "10%"
            }
            taxBracket {
                min = "EUR 6"
                minIncome {
                    amount = "EUR 6"
                }
                tax = "20%"
            }
        }
    }

    println(taxCalculator.calculateTax(income))
}
