/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.aylex.dit

import org.aylex.dit.dsl.Euro
import org.aylex.dit.dsl.Income
import org.aylex.dit.dsl.TaxBracket

class TaxCalculator() {
    private var taxBrackets = listOf<TaxBracket>();

    constructor(taxBrackets: List<TaxBracket>) : this() {
        this.taxBrackets = taxBrackets
    }

    fun calculateTax(income: Income): Euro {
        var tax: Euro = Euro.zero()
        for (taxBracket: TaxBracket in taxBrackets) {
            tax += taxBracket.calculateTax(income)
        }
        return tax;
    }
}
